spring.application.name=airBnbApp

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Default Path Configuration
server.servlet.context-path=/api/v1

jwt.secretKey=a8sd6faihdfjkas2398789afhdskjasdfh87yhk3jha987sdf89aabsdf876

frontend.url=https://localhost:8080